apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::618002461484:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1X0NQIHMIF2AA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::618002461484:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-27T19:59:58Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2020-12-27T19:59:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1640"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b8b6430-ebbb-4c19-80b0-acbcc5aa5331
